name: Test workflow
on: push
env:
  BUILD_NUMBER: ${{ github.sha }}
jobs:
  test1:
    name: Test 1
    runs-on: ubuntu-latest
    steps:
      - name: Setup new env
        id: image-tags
        run: |
          echo "::set-output name=php_image::ABC-${BUILD_NUMBER}"
      - name: Print envs
        env:
          ABC: ${{ steps.image-tags.php_image }}
        run: echo $ABC
