name: not develop and not master
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - closed
      - synchronize
    branches:
      - master
jobs:
  test1:
    name: Test 1
    runs-on: ubuntu-20.04
    steps:
      - name: Print envs
        run: echo job
