name: test
on:
#  pull_request:
#    types:
#      - synchronize
#    branches:
#      - master
  pull_request_target:
    types:
      - opened
      - reopened
      - closed
      - synchronize
#    branches:
#      - test1
jobs:
  test1:
    name: Test 1
    runs-on: ubuntu-20.04
    steps:
      - run: echo Test 1
