name: Test workflow
on:
  workflow_dispatch:  
  push:
    branches:
      - test-dispatch
jobs:
  test1:
    name: Test 1
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo test
